trigger:
- MASTER

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Infra'
    displayName: 'Infra'
    jobs:
    - job: 'CreateResourceGroup'
      displayName: 'Create resource group'
      steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Azure Subscription - Finance.MortgageHub - DevTest'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          scriptPath: "Invoke-AzureDevops.ps1"